[package]
name = "qprotocol"
version.workspace = true
edition.workspace = true
description = "STUN, forward and QUIC packet routing protocol implementation for dquic"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bytes = { workspace = true }
nom = { workspace = true }
dashmap = { workspace = true }
qbase = { workspace = true }
qudp = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[features]
# Enable shorter TTL only for tests (especially integration tests in other crates).
test-ttl = []
