[package]
name = "qtls"
version.workspace = true
edition.workspace = true
description = "Connection-independent QUIC TLS 1.3 state machine for dquic"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
ring = { workspace = true, optional = true }
aws-lc-rs = { version = "1.12", optional = true, default-features = false }
rustls = { git = "https://github.com/genmeta/rustls.git", rev = "22dec513c4ebdf89f113f46e100393cf18963aa6", default-features = false, features = ["std"] }
thiserror = { workspace = true }
x509-parser = { workspace = true }
zeroize = "1.7"

[features]
default = ["ring"]
ring = ["dep:ring", "rustls/ring"]
aws-lc-rs = ["dep:aws-lc-rs", "rustls/aws_lc_rs"]
fips = ["aws-lc-rs", "aws-lc-rs/fips", "rustls/fips"]
